[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz"

[phases.install]
nixPackages = ["python311", "postgresql_16", "gcc"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn connect4_backend.wsgi --log-file -"
